name: YukiTexture
version: 3.0.0
main: net.azisaba.yukitexture.YukiTexture
api-version: 1.16

author: YukiLeafX

commands:
  tex:
    description: プレイヤーにリソースパックを適用します。
    permission: yukitexture.command.texture
    aliases: [ texture, resourcepack, pack ]
  reloadtex:
    description: リソースパックを再読み込みします。
    permission: yukitexture.command.reloadtex

permissions:
  yukitexture.receive:
    default: true
  yukitexture.command.texture:
    default: true
  yukitexture.command.reloadtex:
    default: op
