name: YukiTexture
version: 3.1.0-1.21.1
main: net.azisaba.yukitexture.YukiTexture
api-version: 1.21

author:
- YukiLeafX
- acrylic-style
- sysnote8

commands:
  tex:
    description: プレイヤーにリソースパックを適用します。
    permission: yukitexture.command.texture
    aliases: [ texture, resourcepack, pack ]
  reloadtex:
    description: リソースパックを再読み込みします。
    permission: yukitexture.command.reloadtex
  yukitexture:
    description: YukiTextureの操作用コマンドです。
    permission: yukitexture.command.yukitexture

permissions:
  yukitexture.receive:
    default: true
  yukitexture.command.texture:
    default: true
  yukitexture.command.reloadtex:
    default: op
